// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct VaraSplitClientProgram;
impl sails_rs::client::Program for VaraSplitClientProgram {}
pub trait VaraSplitClient {
    type Env: sails_rs::client::GearEnv;
    fn vara_split(&self) -> sails_rs::client::Service<vara_split::VaraSplitImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> VaraSplitClient
    for sails_rs::client::Actor<VaraSplitClientProgram, E>
{
    type Env = E;
    fn vara_split(&self) -> sails_rs::client::Service<vara_split::VaraSplitImpl, Self::Env> {
        self.service(stringify!(VaraSplit))
    }
}
pub trait VaraSplitClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(self)
    -> sails_rs::client::PendingCtor<VaraSplitClientProgram, io::Create, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> VaraSplitClientCtors
    for sails_rs::client::Deployment<VaraSplitClientProgram, E>
{
    type Env = E;
    fn create(
        self,
    ) -> sails_rs::client::PendingCtor<VaraSplitClientProgram, io::Create, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create () -> ());
}

pub mod vara_split {
    use super::*;
    pub trait VaraSplit {
        type Env: sails_rs::client::GearEnv;
        fn add_expense(
            &mut self,
            group_id: u64,
            payer: ActorId,
            amount: u128,
            description: String,
        ) -> sails_rs::client::PendingCall<io::AddExpense, Self::Env>;
        fn confirm_payment(
            &mut self,
            group_id: u64,
            from: ActorId,
            to: ActorId,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::ConfirmPayment, Self::Env>;
        fn create_group(
            &mut self,
            name: String,
            members: Vec<ActorId>,
        ) -> sails_rs::client::PendingCall<io::CreateGroup, Self::Env>;
        fn settle_group(
            &mut self,
            group_id: u64,
        ) -> sails_rs::client::PendingCall<io::SettleGroup, Self::Env>;
        fn get_balances(
            &self,
            group_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetBalances, Self::Env>;
        fn get_group(
            &self,
            group_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetGroup, Self::Env>;
        fn get_settlement_plan(
            &self,
            group_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetSettlementPlan, Self::Env>;
    }
    pub struct VaraSplitImpl;
    impl<E: sails_rs::client::GearEnv> VaraSplit for sails_rs::client::Service<VaraSplitImpl, E> {
        type Env = E;
        fn add_expense(
            &mut self,
            group_id: u64,
            payer: ActorId,
            amount: u128,
            description: String,
        ) -> sails_rs::client::PendingCall<io::AddExpense, Self::Env> {
            self.pending_call((group_id, payer, amount, description))
        }
        fn confirm_payment(
            &mut self,
            group_id: u64,
            from: ActorId,
            to: ActorId,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::ConfirmPayment, Self::Env> {
            self.pending_call((group_id, from, to, amount))
        }
        fn create_group(
            &mut self,
            name: String,
            members: Vec<ActorId>,
        ) -> sails_rs::client::PendingCall<io::CreateGroup, Self::Env> {
            self.pending_call((name, members))
        }
        fn settle_group(
            &mut self,
            group_id: u64,
        ) -> sails_rs::client::PendingCall<io::SettleGroup, Self::Env> {
            self.pending_call((group_id,))
        }
        fn get_balances(
            &self,
            group_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetBalances, Self::Env> {
            self.pending_call((group_id,))
        }
        fn get_group(
            &self,
            group_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetGroup, Self::Env> {
            self.pending_call((group_id,))
        }
        fn get_settlement_plan(
            &self,
            group_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetSettlementPlan, Self::Env> {
            self.pending_call((group_id,))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AddExpense (group_id: u64, payer: ActorId, amount: u128, description: String) -> super::GroupView);
        sails_rs::io_struct_impl!(ConfirmPayment (group_id: u64, from: ActorId, to: ActorId, amount: u128) -> super::GroupView);
        sails_rs::io_struct_impl!(CreateGroup (name: String, members: Vec<ActorId>) -> super::GroupView);
        sails_rs::io_struct_impl!(SettleGroup (group_id: u64) -> super::GroupSettlement);
        sails_rs::io_struct_impl!(GetBalances (group_id: u64) -> Vec<super::MemberBalance>);
        sails_rs::io_struct_impl!(GetGroup (group_id: u64) -> super::GroupView);
        sails_rs::io_struct_impl!(GetSettlementPlan (group_id: u64) -> Vec<super::SettlementTransfer>);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum VaraSplitEvents {
            GroupCreated {
                group_id: u64,
                name: String,
                members: Vec<ActorId>,
            },
            ExpenseAdded {
                group_id: u64,
                payer: ActorId,
                amount: u128,
                description: String,
            },
            GroupSettled {
                group_id: u64,
                transfers: Vec<SettlementTransfer>,
                total_settled: u128,
            },
            PaymentConfirmed {
                group_id: u64,
                from: ActorId,
                to: ActorId,
                amount: u128,
            },
        }
        impl sails_rs::client::Event for VaraSplitEvents {
            const EVENT_NAMES: &'static [Route] = &[
                "GroupCreated",
                "ExpenseAdded",
                "GroupSettled",
                "PaymentConfirmed",
            ];
        }
        impl sails_rs::client::ServiceWithEvents for VaraSplitImpl {
            type Event = VaraSplitEvents;
        }
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct GroupView {
    pub id: u64,
    pub name: String,
    pub members: Vec<ActorId>,
    pub balances: Vec<MemberBalance>,
    pub expenses: Vec<Expense>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct MemberBalance {
    pub member: ActorId,
    pub balance: i128,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Expense {
    pub payer: ActorId,
    pub amount: u128,
    pub share_per_member: u128,
    pub remainder: u128,
    pub description: String,
    pub created_at: u64,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct GroupSettlement {
    pub group_id: u64,
    pub transfers: Vec<SettlementTransfer>,
    pub total_settled: u128,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct SettlementTransfer {
    pub from: ActorId,
    pub to: ActorId,
    pub amount: u128,
}
